/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthSitesRouteRouteImport } from './routes/_auth/sites/route'
import { Route as AuthSitesIndexRouteImport } from './routes/_auth/sites/index'
import { Route as AuthSitesSiteIdRouteRouteImport } from './routes/_auth/sites/$siteId/route'
import { Route as AuthSitesNewRouteImport } from './routes/_auth/sites/new'
import { Route as AuthSitesSiteIdIndexRouteImport } from './routes/_auth/sites/$siteId/index'
import { Route as AuthSitesSiteIdAnalyticsRouteImport } from './routes/_auth/sites/$siteId/analytics'
import { Route as AuthSitesSiteIdSettingsRouteImport } from './routes/_auth/sites/$siteId/settings'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSitesRouteRoute = AuthSitesRouteRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSitesIndexRoute = AuthSitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSitesRouteRoute,
} as any)
const AuthSitesSiteIdRouteRoute = AuthSitesSiteIdRouteRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => AuthSitesRouteRoute,
} as any)
const AuthSitesNewRoute = AuthSitesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthSitesRouteRoute,
} as any)
const AuthSitesSiteIdIndexRoute = AuthSitesSiteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSitesSiteIdRouteRoute,
} as any)
const AuthSitesSiteIdAnalyticsRoute =
  AuthSitesSiteIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthSitesSiteIdRouteRoute,
  } as any)
const AuthSitesSiteIdSettingsRoute = AuthSitesSiteIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthSitesSiteIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sites': typeof AuthSitesRouteRouteWithChildren
  '/sites/$siteId': typeof AuthSitesSiteIdRouteRouteWithChildren
  '/sites/new': typeof AuthSitesNewRoute
  '/sites/': typeof AuthSitesIndexRoute
  '/sites/$siteId/analytics': typeof AuthSitesSiteIdAnalyticsRoute
  '/sites/$siteId/settings': typeof AuthSitesSiteIdSettingsRoute
  '/sites/$siteId/': typeof AuthSitesSiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthIndexRoute
  '/sites/new': typeof AuthSitesNewRoute
  '/sites': typeof AuthSitesIndexRoute
  '/sites/$siteId/analytics': typeof AuthSitesSiteIdAnalyticsRoute
  '/sites/$siteId/settings': typeof AuthSitesSiteIdSettingsRoute
  '/sites/$siteId': typeof AuthSitesSiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/sites': typeof AuthSitesRouteRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_auth/sites/$siteId': typeof AuthSitesSiteIdRouteRouteWithChildren
  '/_auth/sites/new': typeof AuthSitesNewRoute
  '/_auth/sites/': typeof AuthSitesIndexRoute
  '/_auth/sites/$siteId/analytics': typeof AuthSitesSiteIdAnalyticsRoute
  '/_auth/sites/$siteId/settings': typeof AuthSitesSiteIdSettingsRoute
  '/_auth/sites/$siteId/': typeof AuthSitesSiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/sites'
    | '/sites/$siteId'
    | '/sites/new'
    | '/sites/'
    | '/sites/$siteId/analytics'
    | '/sites/$siteId/settings'
    | '/sites/$siteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/sites/new'
    | '/sites'
    | '/sites/$siteId/analytics'
    | '/sites/$siteId/settings'
    | '/sites/$siteId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/sites'
    | '/_auth/'
    | '/_auth/sites/$siteId'
    | '/_auth/sites/new'
    | '/_auth/sites/'
    | '/_auth/sites/$siteId/analytics'
    | '/_auth/sites/$siteId/settings'
    | '/_auth/sites/$siteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sites': {
      id: '/_auth/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthSitesRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sites/': {
      id: '/_auth/sites/'
      path: '/'
      fullPath: '/sites/'
      preLoaderRoute: typeof AuthSitesIndexRouteImport
      parentRoute: typeof AuthSitesRouteRoute
    }
    '/_auth/sites/$siteId': {
      id: '/_auth/sites/$siteId'
      path: '/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof AuthSitesSiteIdRouteRouteImport
      parentRoute: typeof AuthSitesRouteRoute
    }
    '/_auth/sites/new': {
      id: '/_auth/sites/new'
      path: '/new'
      fullPath: '/sites/new'
      preLoaderRoute: typeof AuthSitesNewRouteImport
      parentRoute: typeof AuthSitesRouteRoute
    }
    '/_auth/sites/$siteId/': {
      id: '/_auth/sites/$siteId/'
      path: '/'
      fullPath: '/sites/$siteId/'
      preLoaderRoute: typeof AuthSitesSiteIdIndexRouteImport
      parentRoute: typeof AuthSitesSiteIdRouteRoute
    }
    '/_auth/sites/$siteId/analytics': {
      id: '/_auth/sites/$siteId/analytics'
      path: '/analytics'
      fullPath: '/sites/$siteId/analytics'
      preLoaderRoute: typeof AuthSitesSiteIdAnalyticsRouteImport
      parentRoute: typeof AuthSitesSiteIdRouteRoute
    }
    '/_auth/sites/$siteId/settings': {
      id: '/_auth/sites/$siteId/settings'
      path: '/settings'
      fullPath: '/sites/$siteId/settings'
      preLoaderRoute: typeof AuthSitesSiteIdSettingsRouteImport
      parentRoute: typeof AuthSitesSiteIdRouteRoute
    }
  }
}

interface AuthSitesSiteIdRouteRouteChildren {
  AuthSitesSiteIdAnalyticsRoute: typeof AuthSitesSiteIdAnalyticsRoute
  AuthSitesSiteIdSettingsRoute: typeof AuthSitesSiteIdSettingsRoute
  AuthSitesSiteIdIndexRoute: typeof AuthSitesSiteIdIndexRoute
}

const AuthSitesSiteIdRouteRouteChildren: AuthSitesSiteIdRouteRouteChildren = {
  AuthSitesSiteIdAnalyticsRoute: AuthSitesSiteIdAnalyticsRoute,
  AuthSitesSiteIdSettingsRoute: AuthSitesSiteIdSettingsRoute,
  AuthSitesSiteIdIndexRoute: AuthSitesSiteIdIndexRoute,
}

const AuthSitesSiteIdRouteRouteWithChildren =
  AuthSitesSiteIdRouteRoute._addFileChildren(AuthSitesSiteIdRouteRouteChildren)

interface AuthSitesRouteRouteChildren {
  AuthSitesSiteIdRouteRoute: typeof AuthSitesSiteIdRouteRouteWithChildren
  AuthSitesNewRoute: typeof AuthSitesNewRoute
  AuthSitesIndexRoute: typeof AuthSitesIndexRoute
}

const AuthSitesRouteRouteChildren: AuthSitesRouteRouteChildren = {
  AuthSitesSiteIdRouteRoute: AuthSitesSiteIdRouteRouteWithChildren,
  AuthSitesNewRoute: AuthSitesNewRoute,
  AuthSitesIndexRoute: AuthSitesIndexRoute,
}

const AuthSitesRouteRouteWithChildren = AuthSitesRouteRoute._addFileChildren(
  AuthSitesRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthSitesRouteRoute: typeof AuthSitesRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSitesRouteRoute: AuthSitesRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
