run-example-compose-app:
	docker-compose --env-file .env.example -f docker-compose.yml up --build
run-example-compose-app-pg:
	docker-compose --env-file .env.example -f docker-compose.postgres.yml up --build