// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type ActivePageStats struct {
	Path string `json:"path"`
	// Number of visitors currently viewing this page
	Visitors int `json:"visitors"`
}

type FilterInput struct {
	// Filter by specific referrer
	Referrer []string `json:"referrer,omitempty"`
	// Filter by device type (desktop, mobile, tablet)
	Device []string `json:"device,omitempty"`
	// Filter by page path
	Page []string `json:"page,omitempty"`
	// Filter by country (stored country name)
	Country []string `json:"country,omitempty"`
}

type GeoIPStatus struct {
	State     string     `json:"state"`
	DbPath    string     `json:"dbPath"`
	Source    *string    `json:"source,omitempty"`
	LastError *string    `json:"lastError,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
