// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type ActivePageStats struct {
	Path string `json:"path"`
	// Number of visitors currently viewing this page
	Visitors int `json:"visitors"`
}

type EventCount struct {
	Event *Event `json:"event"`
	Count int    `json:"count"`
}

type EventCountsResult struct {
	Items []*EventCount `json:"items"`
	Total int           `json:"total"`
}

type FilterInput struct {
	// Filter by specific referrer
	Referrer []string `json:"referrer,omitempty"`
	// Filter by browser type
	Browser []string `json:"browser,omitempty"`
	// Filter by device type (desktop, mobile, tablet, smart-tv, console, watch)
	Device []string `json:"device,omitempty"`
	// Filter by operating system
	Os []string `json:"os,omitempty"`
	// Filter by page path
	Page []string `json:"page,omitempty"`
	// Filter by ISO country code
	Country []string `json:"country,omitempty"`
	// Filter by event type (page view or predefined)
	EventType []EventType `json:"eventType,omitempty"`
	// Filter by event name
	EventName []string `json:"eventName,omitempty"`
	// Filter by event path
	EventPath []string `json:"eventPath,omitempty"`
	// Filter by event definition ID
	EventDefinitionID []string `json:"eventDefinitionId,omitempty"`
}

type GeoIPStatus struct {
	State     GeoIPState `json:"state"`
	DbPath    string     `json:"dbPath"`
	Source    *string    `json:"source,omitempty"`
	LastError *string    `json:"lastError,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type Mutation struct {
}

type PagedCountryStats struct {
	Items         []*CountryStats `json:"items"`
	Total         int             `json:"total"`
	TotalVisitors int             `json:"totalVisitors"`
}

type PagedDeviceStats struct {
	Items         []*DeviceStats `json:"items"`
	Total         int            `json:"total"`
	TotalVisitors int            `json:"totalVisitors"`
}

type PagedOperatingSystemStats struct {
	Items         []*OperatingSystemStats `json:"items"`
	Total         int                     `json:"total"`
	TotalVisitors int                     `json:"totalVisitors"`
}

type PagedPageStats struct {
	Items []*PageStats `json:"items"`
	Total int          `json:"total"`
}

type PagedReferrerStats struct {
	Items []*ReferrerStats `json:"items"`
	Total int              `json:"total"`
}

type PagingInput struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
}

type Query struct {
}

type RegistrationStatus struct {
	HasUsers bool `json:"hasUsers"`
	// Resolved registration policy after the first user exists
	AllowRegistration bool `json:"allowRegistration"`
}

type GeoIPState string

const (
	GeoIPStateDisabled    GeoIPState = "DISABLED"
	GeoIPStateMissing     GeoIPState = "MISSING"
	GeoIPStateDownloading GeoIPState = "DOWNLOADING"
	GeoIPStateReady       GeoIPState = "READY"
	GeoIPStateError       GeoIPState = "ERROR"
)

var AllGeoIPState = []GeoIPState{
	GeoIPStateDisabled,
	GeoIPStateMissing,
	GeoIPStateDownloading,
	GeoIPStateReady,
	GeoIPStateError,
}

func (e GeoIPState) IsValid() bool {
	switch e {
	case GeoIPStateDisabled, GeoIPStateMissing, GeoIPStateDownloading, GeoIPStateReady, GeoIPStateError:
		return true
	}
	return false
}

func (e GeoIPState) String() string {
	return string(e)
}

func (e *GeoIPState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GeoIPState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GeoIPState", str)
	}
	return nil
}

func (e GeoIPState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GeoIPState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GeoIPState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TimeBucket string

const (
	TimeBucketDaily  TimeBucket = "DAILY"
	TimeBucketHourly TimeBucket = "HOURLY"
)

var AllTimeBucket = []TimeBucket{
	TimeBucketDaily,
	TimeBucketHourly,
}

func (e TimeBucket) IsValid() bool {
	switch e {
	case TimeBucketDaily, TimeBucketHourly:
		return true
	}
	return false
}

func (e TimeBucket) String() string {
	return string(e)
}

func (e *TimeBucket) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TimeBucket(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TimeBucket", str)
	}
	return nil
}

func (e TimeBucket) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TimeBucket) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TimeBucket) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
