#!/usr/bin/env bash
set -euo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
temporary_root="$(mktemp -d)"
temporary_repository="$temporary_root/repository"

cleanup() {
  rm -rf "$temporary_root"
}
trap cleanup EXIT

rsync -a \
  --exclude '.git/' \
  --exclude 'dashboard/dist/' \
  --exclude 'dashboard/node_modules/' \
  --exclude 'server/bin/' \
  --exclude 'server/data/' \
  "$repository_root/" "$temporary_repository/"

ln -s "$repository_root/dashboard/node_modules" "$temporary_repository/dashboard/node_modules"

(
  cd "$temporary_repository/dashboard"
  # The temporary tree intentionally reuses the frozen install without allowing pnpm to mutate it.
  ./node_modules/.bin/graphql-codegen --config codegen.ts
)

(
  cd "$temporary_repository/server"
  go generate ./...
)

(
  cd "$temporary_repository/server/static"
  go run build.go
)

for temporary_resolver in "$temporary_repository"/server/internal/graph/*.resolvers.go; do
  relative_resolver="${temporary_resolver#"$temporary_repository/"}"
  repository_resolver="$repository_root/$relative_resolver"

  if [[ ! -f "$repository_resolver" ]]; then
    echo "gqlgen created $relative_resolver; add it as a handwritten feature adapter" >&2
    exit 1
  fi

  if grep -q "Code generated by github.com/99designs/gqlgen" "$repository_resolver"; then
    echo "$relative_resolver must remain handwritten so lint can inspect it" >&2
    exit 1
  fi

  diff -u "$repository_resolver" "$temporary_resolver"
done

generated_paths=(
  "dashboard/src/app/route-tree.gen.ts"
  "dashboard/src/shared/api/generated"
  "server/e2e/generated"
  "server/internal/graph/generated.go"
  "server/internal/graph/model/models_gen.go"
  "server/static/dist"
)

for generated_path in "${generated_paths[@]}"; do
  diff -ru "$repository_root/$generated_path" "$temporary_repository/$generated_path"
done

echo "Generated artifacts are up to date."
