# @genqlient
mutation Register($input: RegisterInput!) {
  register(input: $input) {
    user {
      id
      username
      role
      createdAt
    }
  }
}

# @genqlient
mutation Login($input: LoginInput!) {
  login(input: $input) {
    user {
      id
      username
      role
      createdAt
    }
  }
}

# @genqlient
mutation Logout {
  logout
}

# @genqlient(pointer: true)
query Me {
  me {
    id
    username
    role
    createdAt
  }
}

# @genqlient
query RegistrationStatus {
  registrationStatus {
    hasUsers
    allowRegistration
  }
}
