query Dashboard(
  $siteId: ID!
  # @genqlient(pointer: true)
  $dateRange: DateRangeInput
  # @genqlient(pointer: true, omitempty: true)
  $filter: FilterInput
  $topPagesPaging: PagingInput!
  $referrersPaging: PagingInput!
  $browsersPaging: PagingInput!
  $devicesPaging: PagingInput!
  $osPaging: PagingInput!
  $countriesPaging: PagingInput!
  # @genqlient(pointer: true)
  $dailyStatsBucket: TimeBucket
  $dailyStatsPaging: PagingInput!
) {
  dashboard(siteId: $siteId, dateRange: $dateRange, filter: $filter) {
    visitors
    pageViews
    sessions
    bounceRate
    avgDuration
    topPages(paging: $topPagesPaging) {
      total
      items {
        path
        views
        visitors
      }
    }
    topReferrers(paging: $referrersPaging) {
      total
      items {
        referrer
        visitors
      }
    }
    browsers(paging: $browsersPaging) {
      browser
      visitors
    }
    devices(paging: $devicesPaging) {
      total
      totalVisitors
      items {
        device
        visitors
      }
    }
    operatingSystems(paging: $osPaging) {
      total
      totalVisitors
      items {
        os
        visitors
      }
    }
    countries(paging: $countriesPaging) {
      total
      totalVisitors
      items {
        country {
          code
          name
        }
        visitors
      }
    }
    dailyStats(bucket: $dailyStatsBucket, paging: $dailyStatsPaging) {
      date
      visitors
      pageViews
      sessions
    }
  }
}

# @genqlient
query Realtime($siteId: ID!) {
  realtime(siteId: $siteId) {
    visitors
  }
}

# @genqlient
query Events(
  $siteId: ID!
  # @genqlient(pointer: true)
  $dateRange: DateRangeInput
  $paging: PagingInput!
) {
  events(siteId: $siteId, dateRange: $dateRange, paging: $paging) {
    events {
      id
      name
      path
      properties {
        key
        value
      }
      createdAt
    }
    total
  }
}

query EventCounts($siteId: ID!, $paging: PagingInput!) {
  eventCounts(siteId: $siteId, paging: $paging) {
    total
    items {
      count
      event {
        id
        name
      }
    }
  }
}
